INSERT INTO ACCOUNTS (ACCOUNTID, BALANCE, COMPANYID)  values ('12340', 1000, 'Company1');
INSERT INTO ACCOUNTS (ACCOUNTID, BALANCE, COMPANYID)  values ('12341', 1000, 'Company1');
INSERT INTO ACCOUNTS (ACCOUNTID, BALANCE)  values ('12342', 1000);
INSERT INTO ACCOUNTS (ACCOUNTID, BALANCE, COMPANYID)  values ('12343', 1000, 'Company3');

INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12340', 'CSGN', 20.01, 200, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12340', 'UBSA', 36.67, 30, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12341', 'IBMS', 12.89, 18, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12341', 'VICT', 5.34, 80, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12341', 'TOMA', 36.90, 34, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'CSGN', 57.23, 78, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'POVT', 27.78, 200, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'SECT', 38.12, 34, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'GOBA', 49.89, 67, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'TRET', 50.90, 45, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'WEST', 14.36, 23, now());
INSERT INTO EXECUTIONS (ACCOUNTID, SYMBOL, PRICE, QUANTITY,CURRTIMESTAMP)  values ('12342', 'NORF', 27.47, 78, now());
